### ISSUE TITLE
Allow multiple adapter implementations in runtime at the same time 

### ISSUE THREAD

**Issue by zambrovski** [bpm-crafters/process-engine-api#39]
### Scenario

* Library version: 0.0.1
* Description of your use case: I want to be able to have multiple `process-engine-api` adapters in runtime at the same time, in order to allow for migrations between different engines.

### Current Behaviour

- only one instance of process-engine-api ports is available at runtime by SpringBoot Starter

### Wanted Behaviour

- several instances are available
- this applies to C7 remote and C8 only (there might be only one embedded C7 engine)

### Possible Workarounds

- none

**Comment by zambrovski** [comment]
So I envision the following configuration to be possible:

```
dev:
  bpm-crafters:
    process-api:
      adapter:
        c7:
          embedded:
            external-service-tasks:
              delivery-strategy: embedded_job
              worker-id: embedded-worker
              lock-time-in-seconds: 10
              execute-initial-pull-on-startup: true
            user-tasks:
              delivery-strategy: embedded_job
              execute-initial-pull-on-startup: true
          remote:
            c7-remote-one:
              external-service-tasks:
                delivery-strategy: remote_scheduled
                fixed-rate-schedule-rate: 10
                worker-id: embedded-worker
                lock-time-in-seconds: 10
              user-tasks:
                fixed-rate-schedule-rate: 10
                delivery-strategy: remote_scheduled
            c7-remote-two:
              external-service-tasks:
                delivery-strategy: remote_scheduled
                fixed-rate-schedule-rate: 10
                worker-id: embedded-worker
                lock-time-in-seconds: 10
              user-tasks:
                fixed-rate-schedule-rate: 10
                delivery-strategy: remote_scheduled
        c8:
          c8-one:
            user-tasks:
              delivery-strategy: subscription_refreshing
              fixed-rate-schedule-rate: 2000 # every 2 seconds
              tasklist-url: http://localhost:8082
              fixed-rate-refresh-rate: 2000 # every 2 seconds
              completion-strategy: job
            service-tasks:
              delivery-strategy: subscription
              worker-id: worker
          c8-other:
            user-tasks:
              delivery-strategy: subscription_refreshing
              fixed-rate-schedule-rate: 2000 # every 2 seconds
              tasklist-url: http://localhost:8082
              fixed-rate-refresh-rate: 2000 # every 2 seconds
              completion-strategy: job
            service-tasks:
              delivery-strategy: subscription
              worker-id: worker

```

So the `type` should part of the properties and there should be a named element.
